apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "job-tracker.fullname" . }}-config
  labels:
    {{- include "job-tracker.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
