apiVersion: v1
kind: Secret
metadata:
  name: job-tracker-secrets
  labels:
    {{- include "job-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ "change-me-in-production" | b64enc | quote }}
